name: CI/CD

on:
  push:
    tags:
      - v*
  
jobs:
  flutter_test:
    name: Run Flutter Analyze and Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.5'
          architecture: x64
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze # Lint Check
      - run: flutter format --dry-run --set-exit-if-changed lib/ # Indentation Check
      - run: flutter format --dry-run --set-exit-if-changed test/
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 90


  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: '3.0.5'
          architecture: x64         
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign    
      - run: |
          echo "Creating IPA file from Runner.app"
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app/ build/ios/iphoneos/Payload
          cd build/ios/iphoneos
          zip -r app-unsigned.ipa Payload/Runner.app/
      - run: rm -rf build/ios/iphoneos/Payload
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: app-unsigned-ios
          path: build/ios/iphoneos/app-unsigned.ipa



  
  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
            channel: "stable"
            flutter-version: '3.0.5'
            architecture: x64
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
      - name: Upload Android Bundle
        uses: actions/upload-artifact@v2.1.4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab